spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  #单redis配置
  redis:
    host: 192.168.0.195
    port: 6379
    password:
    database: 6
    timeout: 5s
    redisson:
      file: classpath:redisson-single.yml
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://192.168.0.195:3306/easy_escm?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
          username:
          password:
          driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off
easy:
  escm:
    name: easy-escm
    log-level: INFO
    log-path: ./logs
    token-config:
      is-log: true
      not-check-login-paths: /isLogin,/testAsync
      is-read-body: false
      is-read-cookie: false
      is-read-header: true
    api-decrypt-config:
      header-name: encrypt-flag
      #请求参数解密私钥 对应加密公钥 MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCWxBYyEiXpLt3E4vhd8Z9al0fteU2X2beteDZFG2wyg6Ur5vCBa+EMRFpUrB4duV9e97bpmCgQ1sLhyKGEc8HX4hvuR37GQM4S5t7w3L80K5e6MTNZiwwYuQUNgXuvaO5irtdq0xcNVxoOtvJRCJzBMijBadQMhYgOJ18XqTfFwQIDAQAB
      request-private-key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJbEFjISJeku3cTi+F3xn1qXR+15TZfZt614NkUbbDKDpSvm8IFr4QxEWlSsHh25X173tumYKBDWwuHIoYRzwdfiG+5HfsZAzhLm3vDcvzQrl7oxM1mLDBi5BQ2Be69o7mKu12rTFw1XGg628lEInMEyKMFp1AyFiA4nXxepN8XBAgMBAAECgYEAgu5p5DQUjmywFfOTBGr5HEBzK84Dz9M5C8JxRxToovnm8LiPt6XLfM7Dr/MF+IRrSdtRE46bhPwtpM2LT68D8LU5KGfhscSRuoArlCTN1nbO/Ds8CXYGU39umYOE9ZaLChm+eR/3o9yKiQCXDIjAyqBdeaGkLmM9HvzotIB4cr0CQQDRPRVTBkoSaeVO5stDAvSxVWP8vXjoSBc4FayYDRcxXmamSkCR7ZNx1MukvuUshvld7MD4of/1Bkv7blxEXTijAkEAuHWtrPdtac6Lgs+ImlVqOkBhRNPF9CpuNfn+cm64VaRNo/Kxa4ZOKU32iuu0p7pHAekT6u7XPnrwR6PY0ZP6SwJAGsiL4z3J24OMo8XtPN2y/sQkcWS7hlg8CKTVm/0I+/vOffjBPSzBE/AeRS9eXI3Ge9xjczAheHbe4QdmbiXUqwJAbLDi0q3FKfiL2luhmZdFDegLqLvExBgQcvvJA/Lb6ZL0MOv7wWkVO192K+uxureXybdmhiOQb3+PgBc61luEuwJBAI9OiK9iefB8MJ2u1bbomlwhkHKVwN0Jzu1HjbE+POcS6DPvbIzAU9WvnU3WOvi1M+CUU9rxYvAlnPfmoh4lR24=
      #响应加密公钥 对应加密私钥 MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAK3+xRo+lOoqezAO8LXHCko7UBp51Cw6M6O1NjesfWRHq1ta8tpRkdi4IMGILvj3/69W9ei/gV2HHSKSJBR0lit2uknGb11KFpZWXc2ppDTzZGCzoL7KaGotp/2B/idT/S3pPIoZH4uYSTGXoIp2fK8PpiMdyuXnDKCYnnZGA99nAgMBAAECgYAnmci6hGvYL/sBoSTf+oE5C+7bV8cWmdiO9ft1CGkxna4+iKClV9NeA+pQofIu8CLdgWlOo+eJperXp3NWxII42gaTAIm9GFWQDQt/+wmLJfmi9LuWl/RVmE1hDlfOPILTshGhxxX19VjKxDQBTOa8h8Slh3B2wA5Xl7/6BnmgoQJBAN4iKbbSxI5lJSomg/yfLpvOUvuQ2Aq6UKNJ0LPlndW6R4AcKEUZF0cSVZ5dA9RPZCKULJR3lFJNPwBXsY2V1ZsCQQDIhccauHDhRLEt8KDRuMjWyH8FdPelD9UVnCTHFCIq+CKrw5GHRxsVKoAIY1quZWy6YqyqlkjaenYnfXPx1AAlAkB9N0bKby8rkaqMgx+dtOGiJIE0m+aczYANO9vwvLvnMdWCSt0MbmNnxdcLqSUydfpdX6dtnaa3aiHcgJJu3IqHAkBvviUDHe9BiY8W47YqyMea8WXfe5wZbqY3Aal5Cx4zRc3EXBp4AUb1V5a7lepNrxWVFDHWaiM1JPM89GstQw/FAkEAtpf4SA+vp/CwZM6845wkhU+rxADEq6DCHgBphN/d+dKibeCN2BDRInOrTiGxvFo9+XVVNoqR3//y+m0zfYgoww==
      response-public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCt/sUaPpTqKnswDvC1xwpKO1AaedQsOjOjtTY3rH1kR6tbWvLaUZHYuCDBiC749/+vVvXov4Fdhx0ikiQUdJYrdrpJxm9dShaWVl3NqaQ082Rgs6C+ymhqLaf9gf4nU/0t6TyKGR+LmEkxl6CKdnyvD6YjHcrl5wygmJ52RgPfZwIDAQAB