spring:
  mvc:
    throw-exception-if-no-handler-found: true
  #单redis配置
  redis:
    host: 192.168.0.19
    port: 6379
    password: hse059605
    database: 6
    timeout: 5s
    redisson:
      file: classpath:redisson-single.yml
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://192.168.0.19:3306/easy_escm?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
          username: web
          password: hse059605
          driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off
easy:
  escm:
    log-level: INFO
    log-path: ./logs