spring:
  profiles:
    active: dev
  application:
    name: easy-escm
server:
  port: 39999
  shutdown: graceful
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  global-config:
    #不打印mybatis-plus logo
    banner: false
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ASSIGN_ID:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ASSIGN_ID
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      update-strategy: ignored
  #配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象
  type-aliases-super-type: org.group1418.easy.escm.common.base.CommonMapper
  #别名包扫描路径 注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名
  type-aliases-package: org.group1418.easy.escm.*.*.entity
  type-handlers-package: com.hfy.cloud.common.handlers
  # 原生配置
  configuration:
    #自动驼峰命名规则
    map-underscore-to-camel-case: true
    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
