spring:
  mvc:
    throw-exception-if-no-handler-found: true
  #单redis配置
  redis:
    host: localhost
    port:
    password:
    database: 6
    timeout: 5s
    redisson:
      file: classpath:redisson-single.yml
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://xxxx:3306/easy_escm?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
          username:
          password:
          driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off
easy:
  escm:
    log-level: INFO
    log-path: ./logs